on:
  push
  # pull_request:
  #   types: [opened, reopened, ]

jobs:
  frontend-integration:
    runs-on: self-hosted
    name: Frontend Integration
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          working-directory: frontend
          cache-dependency-path: frontend/package-lock.json
          cache: "npm"
      - run: npm install
        working-directory: frontend
      - run: npm run pre-commit
        working-directory: frontend
      - run: npm run build --if-present
        working-directory: frontend

  backend-integration:
    runs-on: self-hosted
    name: Backend Integration
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          architecture: "x64"
          working-directory: backend
          cache: "pip"
      - name: Install backend modules
        run: pip install -r requirements.txt
        working-directory: backend
      - name: Run migrations
        run: python manage.py migrate
        working-directory: backend
      - name: Run tests
        run: python manage.py test
        working-directory: backend

  cypress-run:
    runs-on: ubuntu-22.04
    needs: [backend-integration, frontend-integration]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v6

        with:
          node-version: "18.x"
          working-directory: frontend
          cache-dependency-path: frontend/package-lock.json
          cache: "npm"
